#ifndef _TAG_H_
#define _TAG_H_

#include "pin.H"

class Tag
{
public:
	UINT16 color;
	UINT16 derivate1 = 0;
	UINT16 derivate2 = 0;

	//Last color generated as a result of mixing some others
	static UINT16 lastColor;

	//New color, directly tainted
	Tag(UINT16 color);

	//Mix two colors
	Tag(UINT16 derivate1, UINT16 derivate2);

	//New color generated by mixing some other two
	Tag(UINT16 color, UINT16 derivate1, UINT16 derivate2);

	//TODO support ternary ops and other
};


#endif