#ifndef _TAG_H_
#define _TAG_H_

#include "pin.H"

/*
	Tags store additional info apart from color information.
*/
class Tag
{
public:
	UINT16 color = 0;
	UINT16 derivate1 = 0;
	UINT16 derivate2 = 0;

	//Last color generated as a result of mixing some others
	static UINT16 lastColor;

	Tag() {};

	//New color, directly tainted
	Tag(UINT16 color);

	//Mix two colors, decide the new color internally
	Tag(UINT16 derivate1, UINT16 derivate2);

	//New color generated by mixing some other two, for mem
	Tag(UINT16 color, UINT16 derivate1, UINT16 derivate2);

	//Mixing colors, for registers, no tags. Returns mixed color
	UINT16 simpleColorMix(UINT16 src1, UINT16 src2);

	//TODO support ternary ops and other
};


#endif