#include "format.h"

std::string getFilenameFullName(std::string filename)
{
	//A suffix to be appended to every file generated by the system, so that we can differentiate between programs
	std::ostringstream str_pid;
	str_pid << getpid();
	std::string pintracerSuffix = std::string(str_pid.str());

	return pintracerSuffix + "_" + filename;
}